### PR TITLE
mechanics for checking paths for media privacy, changing .htaccess if…

### PR DESCRIPTION
**Pull request by Gawrion**
… needed and giving detailed info to user.

Info is given when U change the option. Please analyze and test it.

### CODE REVIEW

**Comment by HuubMons** [comment]
I will test the file before merging. Thanks for the script!

**Comment by Gawrion** [comment]
Sure - it can be further improved. For example a lot more differenciated when it's turned on and off.

**Comment by HuubMons** [comment]
I added an extra branch to test the media security. I will merge these changes into this branch!

**Comment by Gawrion** [comment]
Ok. I will PR changes related to media security into it.

**Comment by Gawrion** [comment]
Principle of this mechanics is good for any files - not only media files.

niedz., 19 paź 2025 o 19:35 Aleksandar N. Kostadinov <
***@***.***> napisał(a):

**Pull request merged**
