### PR TITLE
Media privacy - big change - many hours of analyzing and coding

### PR DESCRIPTION
**Pull request by Gawrion**
Hey Huub! 

Due to (https://humo-gen.com/genforum/viewtopic.php?t=3085) i made new functions for media privacy and tested it. It's working on dev (https://devgene2.tots.pl).

There is a new file give_media_path.php in includes with function give_media_path. It has configurable bool variable simulating option for this which i haven't added. When option is added it should be slightly changed to take option state.
`// untill full code we are simulating options manually changing this bool. If it's false u cant get media old way waith static link. Needs to be replaced by code checking options in db
    // config - change true or false to test. True is old way
    $media_privacy_mode_off = true;`

This function serves linkt to media in 2 ways - old and new for privacy.

If we use the new way - there is query string checker at the begining of layout.php - it checks for query strings and checks the file to serve. It user is authorized - it serves the file by readfile().

I put give_media_path() in all the places i knew the media are served (including thumbnails and non picture media). BTW i repaired some code and upgraded. I think it works better now. I had some problems with relative paths on different levels but finally i managed to solve all of these. I tested both - old and new ways of serving files. I tested thumbnails. I tested subdirs and categories of photos. I tested custom photo dir in new private media mode on  - it's working even if root is domain. I havent tested custom picture dir when humogenfiles are in directory under root, but i think it should work. I tested media picker.

I spent many, many hours solving all of these. I see u made some commits to files i changed, so there could be some conflicts, but it will ez to solve these.

There may be some little changes to these code needed but it's 90% of work done. It would be nice if u add option for these and modify give_media_path function. If u want test it on 'devgene2' i can give u admin credentials by PM.

EDIT: i resynced my local repo to your current version with conflict solving and commited conflict solving so U dont have to ;) Now it's able to merge without conflicts ;)

### CODE REVIEW

**Comment by Gawrion** [comment]
TODO. Analyze give_media_path() and code in layout.php agains traversal attacks. Files are always checked in db before readfile but additional security chcecks are welcome.

**Comment by Gawrion** [comment]
Huub, Christian - on standard media path, and standard files this changes work. But i tested it more completely with custom picture paths, and custom media files like pdf, and there are some warnings and fatals. Some thumbs are not displayed.

The only one conflicts i solved were in file media_inc.php in two places with the same code. When i revert this code to version before Your changes everything works in my fork:
`// $gdmime = get_GDmime(); // a.array
    // $imtype = $gdmime[check_media_type($folder, $file)];
    $imtype = strtoupper(pathinfo($file, PATHINFO_EXTENSION));`
    
Have u tested Your changes with custom picture pathnames and more custom files? Can u pull from my fork (https://github.com/Gawrion/HuMo-genealogy), branch prepare_next_version and see media_inc.php?

U should do it with these 3 commands:
```
git remote add Gawrions-prepare_next_version https://github.com/Gawrion/HuMo-genealogy
git fetch Gawrions-prepare_next_version
git merge Gawrions-prepare_next_version/prepare_next_version
```

**Comment by Gawrion** [comment]
I had a while and analyzed Christian's code - it's broken:
```
$gdmime = get_GDmime(); // a.array it gives (map mime->extensions)
    // next we try to take some data from array based on bool given by check_media_type - it wont give uppercase extension needed in further code
    $imtype = $gdmime[check_media_type($folder, $file)];
```

**Comment by HuubMons** [comment]
Ok, merged! Thanks for coding!

I will do some tests later.

**Pull request merged**
