### PR TITLE
random photo - man's and woman's names in family photo link based on privacy

### PR DESCRIPTION
**Pull request by Gawrion**
I think the last thing is done in this random photo function befor release. :D 

I forget to change number of chars limit for text from 50 to 100 (in two places).
U can also port the same method of limiting text in lightbox picture - but there it can be 2-4 times longer, becouse with long texts the photo cant be seen especially in smaller windows

Change the code for language versions compatiblity.

ps. When privacy is checked for family photo it's not displayed. Am I right? Than two versions of link texts are not required. Am i right? :/

----

Also a little change to lightbox css to look nicer:
look: https://devgene.tots.pl/

### CODE REVIEW

**Comment by HuubMons** [comment]
I will check this pull request. At this moment there are 2 conflicts, and I'm not experienced yet merging scripts from other programmers. Still learning how to use Github.

**Comment by HuubMons** [comment]
I have merged the changed, and will check the names of man and woman.
There is a general function to show names, this will check privacy filter, and also show prefix of last name (used in The Netherlands and Belgium).

Show name:
$name = $person_cls->person_name($personDb);
echo $name["standard_name"];

Thanks for the updates!

**Comment by Gawrion** [comment]
Huub - no problem - i just started to use git yesterday due to contribute HuMoGen ;) We're both learning. IDK why there are conflicts here... I was simple change. 
I did some conflict resolvation while i was pulling your changes to my fork and that was piece of cake.

**Comment by HuubMons** [comment]
> When privacy is checked for family photo it's not displayed. Am I right?

The privacy part for family photo's isn't correct at this moment. I will change it.
If a connected person has an active privacy filter, the photo will be skipped and the next photo will be checked.

**Comment by HuubMons** [comment]
Update: I rebuild the privacy filter for the random photo. It will check man and woman for photo's connected to relations.
A photo will only be shown if connected persons are allowed to see for visitor of page.

**Comment by Gawrion** [comment]
I was thinking about exactly the same logic. GJ!

**Pull request merged**
